# Generated by Django 5.2.4 on 2025-07-20 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_userprofile_calories_per_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutrecommendation',
            name='posture_analysis',
        ),
        migrations.DeleteModel(
            name='PostureAnalysis',
        ),
    ]
