# Generated by Django 4.2 on 2025-07-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_fooditem_meallog_dailysummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysummary',
            name='total_fiber',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='total_sodium',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='total_sugar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='fiber',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='sodium',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='sugar',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='meallog',
            name='fiber',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='meallog',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], default='snack', max_length=20),
        ),
        migrations.AddField(
            model_name='meallog',
            name='sodium',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='meallog',
            name='source',
            field=models.CharField(default='AI', max_length=20),
        ),
        migrations.AddField(
            model_name='meallog',
            name='sugar',
            field=models.FloatField(default=0),
        ),
    ]
