# Generated by Django 5.2.4 on 2025-09-26 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_dailysummary_total_fiber_dailysummary_total_sodium_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.CharField(choices=[('squats', 'Squats'), ('pushups', 'Push-ups'), ('bicep_curls', 'Bicep Curls'), ('hammer_curls', 'Hammer Curls'), ('side_raises', 'Side Raises')], max_length=50)),
                ('reps', models.IntegerField(default=0)),
                ('reps_left', models.IntegerField(default=0)),
                ('reps_right', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration_seconds', models.IntegerField(default=0)),
                ('calories_burned', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
    ]
