# Generated by Django 5.2.4 on 2026-05-20 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_dailysummary_total_fiber_dailysummary_total_sodium_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostureAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=100)),
                ('posture_score', models.FloatField(help_text='Alignment score percentage')),
                ('feedback', models.TextField(help_text='Form correction feedback')),
                ('improvement_tips', models.JSONField(default=list, help_text='Biomechanical corrective tips')),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-analysis_date'],
            },
        ),
    ]
