# Generated by Django 5.2.4 on 2026-06-14 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_postureanalysis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=100)),
                ('sets', models.PositiveIntegerField(default=1)),
                ('reps', models.PositiveIntegerField(default=0)),
                ('weight', models.FloatField(default=0.0, help_text='Weight in kg')),
                ('date', models.DateField(auto_now_add=True)),
                ('duration_minutes', models.PositiveIntegerField(default=10)),
                ('muscle_group', models.CharField(help_text='Legs, Chest, Biceps, Shoulders, Back, etc.', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
