# Generated by Django 5.2.5 on 2026-06-26 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0009_foodpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.PositiveIntegerField()),
                ('reps', models.PositiveIntegerField(default=0)),
                ('weight', models.FloatField(default=0.0)),
                ('unit', models.CharField(default='kg', max_length=5)),
                ('with_spotter', models.BooleanField(default=False)),
                ('to_failure', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=100)),
                ('workout_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sets', to='workouts.workoutlog')),
            ],
            options={
                'ordering': ['set_number'],
            },
        ),
    ]
