# Generated by Django 5.2.5 on 2026-06-26 12:56

import django.db.models.deletion
from django.db import migrations, models


def populate_exercises_and_map_logs(apps, schema_editor):
    Exercise = apps.get_model('workouts', 'Exercise')
    WorkoutLog = apps.get_model('workouts', 'WorkoutLog')

    # Define standard exercises
    EXERCISE_REGISTRY_DATA = {
        101: {
            "name": "Dumbbell Curl",
            "muscle_group": "Biceps",
            "aliases": [
                "Dumbbell Curl", "Bicep Dumbbell Curl", "Standing Dumbbell Curl", "DB Curl",
                "Dumbbell Biceps Curl", "Alternating Dumbbell Curl", "Alternating DB Curl",
                "Two Arm Dumbbell Curl", "Both Arm Curl", "Classic Dumbbell Curl",
                "Dumbell Curl", "Bicep Dumbell Curl", "Standing Dumbell Curl", "Alternating Dumbell Curl",
                "Two Arm Dumbell Curl", "Classic Dumbell Curl", "Bicep Curl", "Bicep Curls", "Biceps curls", "Biceps Curl", "db curls"
            ]
        },
        102: {
            "name": "Hammer Curl",
            "muscle_group": "Biceps",
            "aliases": [
                "Hammer Curl", "Dumbbell Hammer Curl", "Neutral Grip Curl", "Standing Hammer Curl",
                "DB Hammer Curl", "Cross Body Hammer Curl", "Dumbell Hammer Curl", "Standing Dumbell Hammer Curl"
            ]
        },
        103: {
            "name": "Barbell Curl",
            "muscle_group": "Biceps",
            "aliases": [
                "Barbell Curl", "BB Curl", "Standing Barbell Curl", "EZ Bar Curl", "EZ Curl",
                "Barbell Curls", "BB Curls", "Standing Barbell Curls", "EZ Curls"
            ]
        },
        104: {
            "name": "Bench Press",
            "muscle_group": "Chest",
            "aliases": [
                "Bench Press", "Flat Bench Press", "Barbell Bench Press", "BB Bench Press", "Flat BB Bench",
                "Bench presses", "Flat bench presses", "Barbell bench presses"
            ]
        },
        105: {
            "name": "Incline Bench Press",
            "muscle_group": "Chest",
            "aliases": [
                "Incline Bench Press", "Incline BB Press", "Incline Barbell Press", "Incline Chest Press",
                "Incline bench presses", "Incline bb presses", "Incline barbell presses"
            ]
        },
        106: {
            "name": "Dumbbell Bench Press",
            "muscle_group": "Chest",
            "aliases": [
                "DB Bench Press", "Dumbbell Bench Press", "Flat Dumbbell Press", "Flat DB Press",
                "DB bench presses", "Dumbbell bench presses", "Dumbell bench press", "Dumbell bench presses",
                "Flat dumbell press"
            ]
        },
        107: {
            "name": "Incline Dumbbell Press",
            "muscle_group": "Chest",
            "aliases": [
                "Incline DB Press", "Incline Dumbbell Press", "Incline Chest Dumbbell Press",
                "Incline db presses", "Incline dumbbell presses", "Incline chest dumbell press", "Incline dumbell press"
            ]
        },
        108: {
            "name": "Shoulder Press",
            "muscle_group": "Shoulders",
            "aliases": [
                "Shoulder Press", "Overhead Press", "Military Press", "Standing Shoulder Press", "OHP",
                "Shoulder presses", "Overhead presses", "Military presses", "Standing shoulder presses"
            ]
        },
        109: {
            "name": "Dumbbell Shoulder Press",
            "muscle_group": "Shoulders",
            "aliases": [
                "DB Shoulder Press", "Dumbbell Shoulder Press", "Seated DB Press", "Seated Shoulder Press",
                "DB shoulder presses", "Dumbbell shoulder presses", "Dumbell shoulder press", "Seated dumbell press"
            ]
        },
        110: {
            "name": "Lateral Raise",
            "muscle_group": "Shoulders",
            "aliases": [
                "Lateral Raise", "Side Raise", "DB Lateral Raise", "Side Lateral Raise",
                "Lateral raises", "Side raises", "DB lateral raises", "Side lateral raises"
            ]
        },
        111: {
            "name": "Front Raise",
            "muscle_group": "Shoulders",
            "aliases": [
                "Front Raise", "DB Front Raise", "Front Dumbbell Raise",
                "Front raises", "DB front raises", "Front dumbell raise"
            ]
        },
        112: {
            "name": "Rear Delt Fly",
            "muscle_group": "Shoulders",
            "aliases": [
                "Rear Delt Fly", "Reverse Fly", "Bent Over Reverse Fly", "Rear Fly",
                "Rear delt flies", "Reverse flies", "Bent over reverse flies", "Rear flies"
            ]
        },
        113: {
            "name": "Lat Pulldown",
            "muscle_group": "Back",
            "aliases": [
                "Lat Pulldown", "Wide Grip Lat Pulldown", "Cable Lat Pulldown", "Pulldown",
                "Lat pulldowns", "Wide grip lat pulldowns", "Cable lat pulldowns", "Pulldowns"
            ]
        },
        114: {
            "name": "Seated Cable Row",
            "muscle_group": "Back",
            "aliases": [
                "Cable Row", "Seated Cable Row", "Machine Row", "Low Row",
                "Cable rows", "Seated cable rows", "Machine rows", "Low rows"
            ]
        },
        115: {
            "name": "Bent Over Row",
            "muscle_group": "Back",
            "aliases": [
                "Barbell Row", "Bent Over Row", "BB Row", "Bent Row",
                "Barbell rows", "Bent over rows", "BB rows", "Bent rows"
            ]
        },
        116: {
            "name": "Pull Up",
            "muscle_group": "Back",
            "aliases": [
                "Pull Up", "Pull-Up", "Wide Pull Up", "Bodyweight Pull Up",
                "Pull ups", "Pull-ups", "Wide pull ups", "Bodyweight pull ups"
            ]
        },
        117: {
            "name": "Deadlift",
            "muscle_group": "Back",
            "aliases": [
                "Deadlift", "Conventional Deadlift", "Barbell Deadlift", "BB Deadlift",
                "Deadlifts", "Conventional deadlifts", "Barbell deadlifts", "BB deadlifts"
            ]
        },
        118: {
            "name": "Romanian Deadlift",
            "muscle_group": "Legs",
            "aliases": [
                "Romanian Deadlift", "RDL", "Barbell RDL", "DB Romanian Deadlift",
                "Romanian deadlifts", "RDLs", "Barbell RDLs", "DB Romanian deadlifts"
            ]
        },
        119: {
            "name": "Squat",
            "muscle_group": "Legs",
            "aliases": [
                "Squat", "Back Squat", "Barbell Squat", "BB Squat",
                "Squats", "Back squats", "Barbell squats", "BB squats"
            ]
        },
        120: {
            "name": "Front Squat",
            "muscle_group": "Legs",
            "aliases": [
                "Front Squat", "Barbell Front Squat",
                "Front squats", "Barbell front squats"
            ]
        },
        121: {
            "name": "Leg Press",
            "muscle_group": "Legs",
            "aliases": [
                "Leg Press", "Machine Leg Press", "45 Degree Leg Press",
                "Leg presses", "Machine leg presses"
            ]
        },
        122: {
            "name": "Leg Extension",
            "muscle_group": "Legs",
            "aliases": [
                "Leg Extension", "Quad Extension", "Machine Leg Extension",
                "Leg extensions", "Quad extensions", "Machine leg extensions"
            ]
        },
        123: {
            "name": "Leg Curl",
            "muscle_group": "Legs",
            "aliases": [
                "Leg Curl", "Hamstring Curl", "Lying Leg Curl", "Seated Leg Curl",
                "Leg curls", "Hamstring curls", "Lying leg curls", "Seated leg curls"
            ]
        },
        124: {
            "name": "Calf Raise",
            "muscle_group": "Legs",
            "aliases": [
                "Standing Calf Raise", "Calf Raise", "Seated Calf Raise", "Machine Calf Raise",
                "Standing calf raises", "Calf raises", "Seated calf raises", "Machine calf raises"
            ]
        },
        125: {
            "name": "Hip Thrust",
            "muscle_group": "Legs",
            "aliases": [
                "Hip Thrust", "Barbell Hip Thrust", "Glute Bridge",
                "Hip thrusts", "Barbell hip thrusts", "Glute bridges"
            ]
        },
        126: {
            "name": "Chest Fly",
            "muscle_group": "Chest",
            "aliases": [
                "Chest Fly", "Pec Deck", "Machine Fly", "Cable Fly", "Dumbbell Fly",
                "Chest flies", "Pec decks", "Machine flies", "Cable flies", "Dumbbell flies", "Dumbell fly"
            ]
        },
        127: {
            "name": "Tricep Pushdown",
            "muscle_group": "Triceps",
            "aliases": [
                "Tricep Pushdown", "Cable Pushdown", "Rope Pushdown", "Straight Bar Pushdown",
                "Tricep pushdowns", "Cable pushdowns", "Rope pushdowns", "Straight bar pushdowns"
            ]
        },
        128: {
            "name": "Overhead Tricep Extension",
            "muscle_group": "Triceps",
            "aliases": [
                "Overhead Tricep Extension", "DB Overhead Extension", "Skull Crusher",
                "Overhead tricep extensions", "DB overhead extensions", "Skull crushers"
            ]
        },
        129: {
            "name": "Dips",
            "muscle_group": "Chest",
            "aliases": [
                "Dips", "Parallel Bar Dips", "Chest Dips", "Tricep Dips",
                "Dip", "Parallel bar dip", "Chest dip", "Tricep dip"
            ]
        }
    }

    # Populate Exercise model
    created_exercises = {}
    for ex_id, data in EXERCISE_REGISTRY_DATA.items():
        exercise, _ = Exercise.objects.get_or_create(
            id=ex_id,
            defaults={
                "name": data["name"],
                "muscle_group": data["muscle_group"],
                "aliases": data["aliases"]
            }
        )
        created_exercises[ex_id] = exercise

    # Map legacy WorkoutLogs to Exercises
    for log in WorkoutLog.objects.all():
        name = log.exercise_name.strip() if log.exercise_name else ""
        if not name:
            continue
            
        matched_id = None
        lower_name = name.lower()
        
        # Check explicit aliases
        for ex_id, data in EXERCISE_REGISTRY_DATA.items():
            if lower_name in [alias.lower() for alias in data["aliases"]]:
                matched_id = ex_id
                break

        # Fallbacks for fuzzy name matches
        if not matched_id:
            if "bicep" in lower_name and "curl" in lower_name:
                if "hammer" in lower_name:
                    matched_id = 102
                elif "barbell" in lower_name or "ez" in lower_name:
                    matched_id = 103
                else:
                    matched_id = 101
            elif "bench" in lower_name and "press" in lower_name:
                if "incline" in lower_name:
                    if "dumbbell" in lower_name or "db" in lower_name:
                        matched_id = 107
                    else:
                        matched_id = 105
                elif "dumbbell" in lower_name or "db" in lower_name:
                    matched_id = 106
                else:
                    matched_id = 104
            elif "squat" in lower_name:
                if "front" in lower_name:
                    matched_id = 120
                else:
                    matched_id = 119
            elif "deadlift" in lower_name:
                if "romanian" in lower_name or "rdl" in lower_name:
                    matched_id = 118
                else:
                    matched_id = 117
            elif "shoulder" in lower_name or "overhead" in lower_name or "military" in lower_name:
                if "dumbbell" in lower_name or "db" in lower_name:
                    matched_id = 109
                else:
                    matched_id = 108
            elif "lateral" in lower_name and "raise" in lower_name:
                matched_id = 110
            elif "front" in lower_name and "raise" in lower_name:
                matched_id = 111
            elif "rear" in lower_name and "fly" in lower_name:
                matched_id = 112
            elif "lat" in lower_name and "pulldown" in lower_name:
                matched_id = 113
            elif "cable" in lower_name and "row" in lower_name:
                matched_id = 114
            elif "row" in lower_name:
                matched_id = 115
            elif "pull" in lower_name and "up" in lower_name:
                matched_id = 116
            elif "leg" in lower_name and "press" in lower_name:
                matched_id = 121
            elif "extension" in lower_name:
                matched_id = 122
            elif "leg" in lower_name and "curl" in lower_name:
                matched_id = 123
            elif "calf" in lower_name:
                matched_id = 124
            elif "thrust" in lower_name:
                matched_id = 125
            elif "fly" in lower_name:
                matched_id = 126
            elif "pushdown" in lower_name:
                matched_id = 127
            elif "tricep" in lower_name and "extension" in lower_name:
                matched_id = 128
            elif "dip" in lower_name:
                matched_id = 129
                
        if matched_id:
            log.exercise = created_exercises[matched_id]
            log.save()


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0010_setlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('muscle_group', models.CharField(max_length=50)),
                ('aliases', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workouts.exercise'),
        ),
        migrations.RunPython(populate_exercises_and_map_logs),
    ]
